name: Validate
on: [push, pull_request]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: make deps
      - name: Validate
        run: make validate
      - name: Check Format
        run: npx prettier --check schema.json "vendor/**/*.yaml"
